ALTER TABLE TAG DROP CONSTRAINT IF EXISTS ID_TAG_AVALIACAO_FK;
ALTER TABLE TAG ADD CONSTRAINT ID_TAG_AVALIACAO_FK FOREIGN KEY (ID_AVALIACAO) REFERENCES AVALIACAO(ID) ON DELETE CASCADE;

ALTER TABLE FOTO DROP CONSTRAINT IF EXISTS ID_FOTO_AVALIACAO_FK;
ALTER TABLE FOTO ADD CONSTRAINT ID_FOTO_AVALIACAO_FK FOREIGN KEY (ID_AVALIACAO) REFERENCES AVALIACAO(ID) ON DELETE CASCADE;
