ALTER TABLE USUARIO_CURTE_AVALIACAO DROP CONSTRAINT ID_CURTE_AVALIACAO_FK;
ALTER TABLE USUARIO_CURTE_AVALIACAO ADD CONSTRAINT ID_CURTE_AVALIACAO_FK FOREIGN KEY (ID_AVALIACAO) REFERENCES AVALIACAO(ID) ON DELETE CASCADE;

ALTER TABLE USUARIO_COMENTA_AVALIACAO DROP CONSTRAINT ID_COMENTA_AVALIACAO_FK;
ALTER TABLE USUARIO_COMENTA_AVALIACAO ADD CONSTRAINT ID_COMENTA_AVALIACAO_FK FOREIGN KEY (ID_AVALIACAO) REFERENCES AVALIACAO(ID) ON DELETE CASCADE;
