ALTER TABLE USUARIO_CURTE_AVALIACAO ADD COLUMN ID SERIAL;
ALTER TABLE USUARIO_CURTE_AVALIACAO DROP CONSTRAINT ID_CURTE_PK;
ALTER TABLE USUARIO_CURTE_AVALIACAO ADD CONSTRAINT USUARIO_CURTE_AVALIACAO_PK PRIMARY KEY (ID);

ALTER TABLE USUARIO_COMENTA_AVALIACAO ADD COLUMN ID SERIAL;
ALTER TABLE USUARIO_COMENTA_AVALIACAO DROP CONSTRAINT ID_COMENTA_PK;
ALTER TABLE USUARIO_COMENTA_AVALIACAO ADD CONSTRAINT USUARIO_COMENTA_AVALIACAO_PK PRIMARY KEY (ID);
