ALTER TABLE USUARIO_FAVORITA_ESTABELECIMENTO ADD COLUMN ID SERIAL;
ALTER TABLE USUARIO_FAVORITA_ESTABELECIMENTO DROP CONSTRAINT ID_FAVORITA_PK;
ALTER TABLE USUARIO_FAVORITA_ESTABELECIMENTO ADD CONSTRAINT USUARIO_FAVORITA_ESTABELECIMENTO_PK PRIMARY KEY (ID);
