CREATE OR REPLACE VIEW V_USUARIO
AS
SELECT U.ID,
       U.EMAIL,
       U.SENHA,
       U.NOME,
       U.USERNAME,
       U.DT_NASCIMENTO,
       U.FOTO,
       U.STATUS,
       COUNT(A.ID) AS AVALIACOES
FROM USUARIO U
         LEFT JOIN AVALIACAO A ON A.ID_USUARIO = U.ID
GROUP BY U.ID, U.EMAIL, U.SENHA, U.NOME, U.USERNAME, U.DT_NASCIMENTO, U.FOTO, U.STATUS;