CREATE OR REPLACE VIEW PUBLIC.V_ESTABELECIMENTO
AS
SELECT E.ID,
       E.NOME,
       E.CATEGORIA,
       E.RUA,
       E.NUMERO,
       E.BAIRRO,
       E.CIDADE,
       E.ESTADO,
       E.CEP,
       CONCAT_WS(' '::TEXT, E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO, E.CEP) AS LOCALIZACAO,
       COUNT(A.ID) AS AVALIACOES,
       AVG(A.NOTA_GERAL) AS NOTA_GERAL,
       BOOL_OR(F.ID IS NOT NULL) AS FAVORITADO
FROM ESTABELECIMENTO E
         LEFT JOIN AVALIACAO A ON E.ID = A.ID_ESTABELECIMENTO
         LEFT JOIN USUARIO_FAVORITA_ESTABELECIMENTO F ON E.ID = F.ID_ESTABELECIMENTO
GROUP BY E.ID, E.NOME, E.CATEGORIA, E.RUA, E.NUMERO, E.BAIRRO, E.CIDADE, E.ESTADO, E.CEP;