CREATE OR REPLACE VIEW V_ESTABELECIMENTO AS
SELECT E.ID,
       E.NOME,
       E.CATEGORIA,
       E.RUA,
       E.NUMERO,
       E.BAIRRO,
       E.CIDADE,
       E.ESTADO,
       E.CEP,
       CONCAT_WS(' '::TEXT, E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO, E.CEP) AS LOCALIZACAO,
       COUNT(A.ID) AS AVALIACOES,
       AVG(A.NOTA_GERAL) AS NOTA_GERAL
FROM ESTABELECIMENTO E
         LEFT JOIN AVALIACAO A ON E.ID = A.ID_ESTABELECIMENTO
GROUP BY E.ID, E.NOME, E.CATEGORIA, E.RUA, E.NUMERO, E.BAIRRO, E.CIDADE, E.ESTADO, E.CEP;
