CREATE OR REPLACE VIEW V_AVALIACAO
AS
SELECT A.ID,
       A.ID_USUARIO,
       A.ID_ESTABELECIMENTO,
       A.CONSUMO,
       A.DESCRICAO,
       A.PRECO,
       A.NOTA_GERAL,
       A.NOTA_COMIDA,
       A.NOTA_ATENDIMENTO,
       A.NOTA_AMBIENTE,
       A.DATA,
       COALESCE(C.QTDCURTIDAS, 0::BIGINT) AS CURTIDAS,
       COALESCE(COM.QTDCOMENTARIOS, 0::BIGINT) AS COMENTARIOS
FROM AVALIACAO A
         LEFT JOIN (SELECT UC.ID_AVALIACAO,
                           COUNT(*) AS QTDCURTIDAS
                    FROM USUARIO_CURTE_AVALIACAO UC
                    GROUP BY UC.ID_AVALIACAO) C
                   ON C.ID_AVALIACAO = A.ID
         LEFT JOIN (SELECT UCOM.ID_AVALIACAO,
                           COUNT(*) AS QTDCOMENTARIOS
                    FROM USUARIO_COMENTA_AVALIACAO UCOM
                    GROUP BY UCOM.ID_AVALIACAO) COM
                   ON COM.ID_AVALIACAO = A.ID;