ALTER TABLE AVALIACAO DROP CONSTRAINT CHECK_NOTA_GERAL_VALIDA;
ALTER TABLE AVALIACAO ADD CONSTRAINT CHECK_NOTA_GERAL_VALIDA CHECK (NOTA_GERAL IN (0, 1, 2, 3, 4, 5));

ALTER TABLE AVALIACAO DROP CONSTRAINT CHECK_NOTA_COMIDA_VALIDA;
ALTER TABLE AVALIACAO ADD CONSTRAINT CHECK_NOTA_COMIDA_VALIDA CHECK (NOTA_COMIDA IN (0, 1, 2, 3, 4, 5));

ALTER TABLE AVALIACAO DROP CONSTRAINT CHECK_NOTA_ATENDIMENTO_VALIDA;
ALTER TABLE AVALIACAO ADD CONSTRAINT CHECK_NOTA_ATENDIMENTO_VALIDA CHECK (NOTA_ATENDIMENTO IN (0, 1, 2, 3, 4, 5));

ALTER TABLE AVALIACAO DROP CONSTRAINT CHECK_NOTA_AMBIENTE_VALIDA;
ALTER TABLE AVALIACAO ADD CONSTRAINT CHECK_NOTA_AMBIENTE_VALIDA CHECK (NOTA_AMBIENTE IN (0, 1, 2, 3, 4, 5));